/* ZX7981PG */

#define BOARD_PID		"ZX7981PG"
#define BOARD_NAME		"ZX7981PG"
#define BOARD_DESC		"ZX7981PG MT7981B 5G CPE router"
#define BOARD_VENDOR_NAME	"ZX"
#define BOARD_VENDOR_URL	""
#define BOARD_MODEL_URL		""
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120

#define BOARD_HAS_5G_11AC		1
#define BOARD_HAS_5G_11AX		1
#define BOARD_HAS_2G_11AX		1
#define BOARD_NUM_ANT_5G_TX		2
#define BOARD_NUM_ANT_5G_RX		2
#define BOARD_NUM_ANT_2G_TX		2
#define BOARD_NUM_ANT_2G_RX		2
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_ETH_LEDS		0
#define BOARD_NUM_UPHY_USB3		0
#define BOARD_USB_PORT_SWAP		0


#define USE_IPV6 1
